# Site Info
title: CyberID
tagline: 'Small things that matters'
description: 'Personal list and essay for learning purpose only, my text logs in learning everything from the Internet'
baseurl: ''
url: https://cyberid.github.io
logo: '/public/cyberidlogo.jpg'

# Site configurations
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 3
paginate_path: '/page:num'
permalink: /:title/

version: 1.0.0

# About/contact
author:
  name: CyberID
  description: Small things that matters.
  contact:
    #linkedin:  <hide>
    github:    https://https://github.com/cyberid
    # facebook:  <hide>
    #twitter:   <hide>
    #weibo:     <hide>
    #email:     <hide>

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Categories:           
    - '/categories/'
  Tags:
    - '/tags/'
  About:          
    - '/about/'
  Github Project: 
    - 'https://cyberid.github.io'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus
