# Site Info
title: CyberID
tagline: 'Small things that matters'
description: 'Personal list and essay for learning purpose only, my text logs in learning everything from the Internet'
baseurl: ''
url: https://cyberid.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/page:num'
permalink: /:title/

version: 1.0.0

# About/contact
author:
  name: CyberID
  description: Small things that matters.
  contact:
    linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/codinfox
    # facebook:  <hide>
    twitter:   https://twitter.com/Li_Zhihao
    weibo:     http://weibo.com/41173780
    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Categories:           
    - '/categories/'
  Tags:
    - '/tags/'
  About:          
    - '/about/'
  Github Project: 
    - 'https://cyberid.github.io'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus
